### PR TITLE
Removing extra esi:remove close from the relative date example.

### PR DESCRIPTION
**Pull request by dcmoore-gd**
Main part of this is to remove an extra `</esi:remove>` from the example.

Also he [fiddle itself](https://fiddle.fastlydemo.net/fiddle/fd2dfedf) isn't working due to a 403, and @jlcross noticed this while looking into why.  In my testing it doesn't fix the problem though, which I tested with this fiddle:  https://fiddle.fastlydemo.net/fiddle/b2fdbe19

### CODE REVIEW

**Comment by dcmoore-gd** [comment]
The error with the Fiddle seems to be related to throwing an `error 900`.  `error 700` works just fine as demonstrated here:  https://fiddle.fastlydemo.net/fiddle/19d66810

**Comment by dcmoore-gd** [comment]
@triblondon I noticed some recent activity on this repo, figured I'd ping with this change again :)

**Comment by triblondon** [comment]
My goodness, I’m so sorry. Thanks for this!

**Comment by dcmoore-gd** [comment]
Heh, no worries @triblondon!  Actually are these even linked to anymore?  If so you might want to fix the fiddle as mentioned above:  https://github.com/triblondon/fastly-fiddle-examples/pull/1#issuecomment-543240413

**Comment by dcmoore-gd** [comment]
Oh and thanks for all these examples!  They really helped!

**Comment by triblondon** [comment]
The canonical fiddle has actually been updated to use 600, which is in the range Fastly now recommends for customer use:
https://developer.fastly.com/solutions/examples/relative-date-insertion-using-esi

Fiddles are immutable so there's not much I can do about copies that have already been made unfortunately.

**Comment by dcmoore-gd** [comment]
Of course, thanks @triblondon!  I hadn't noticed that it was updated there.

In case anyone finds this thread, that range is now documented here:  https://developer.fastly.com/reference/vcl/statements/error/#best-practices-for-using-status-codes-for-errors

**Pull request merged**
